// <auto-generated />
using System;
using InsuranceClaim.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceClaim.Server.Migrations
{
    [DbContext(typeof(InsuranceClaimDBContext))]
    [Migration("20250217085750_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceClaim.Server.Models.PaymentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PaymentClaimantCost")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentDefenceCost")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentModel");
                });

            modelBuilder.Entity("InsuranceClaim.Server.Models.ReserveModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IncurredClaimantCost")
                        .HasColumnType("bigint");

                    b.Property<long>("IncurredDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("IncurredDefenceCost")
                        .HasColumnType("bigint");

                    b.Property<long>("PaidClaimantCost")
                        .HasColumnType("bigint");

                    b.Property<long>("PaidDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("PaidDefenceCost")
                        .HasColumnType("bigint");

                    b.Property<long>("ReserveClaimantCost")
                        .HasColumnType("bigint");

                    b.Property<long>("ReserveDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("ReserveDefenceCost")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReserveModel");
                });
#pragma warning restore 612, 618
        }
    }
}
